import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { Vault } from "./vault.js";
import type { Credential } from "./credentials.js";

/**
 * Pure, testable core of the onboarding CLI (no prompts, no self-execution). The interactive shell
 * lives in `onboard.ts`.
 */

export interface AppSpec {
  readonly key: string;
  readonly label: string;
  readonly urlEnv: string;
  readonly extraEnv?: { flag: string; env: string; prompt: string }[];
  readonly authHint: string;
}

export const APPS: AppSpec[] = [
  { key: "jira", label: "Jira", urlEnv: "HELMSMAN_JIRA_URL", authHint: "Cloud: basic (email + API token). Server/DC: pat." },
  { key: "confluence", label: "Confluence", urlEnv: "HELMSMAN_CONFLUENCE_URL", authHint: "Cloud: basic (email + API token)." },
  {
    key: "bitbucket",
    label: "Bitbucket / Stash (Server/DC)",
    urlEnv: "HELMSMAN_BITBUCKET_URL",
    extraEnv: [
      { flag: "project", env: "HELMSMAN_BITBUCKET_PROJECT", prompt: "Bitbucket project key (e.g. APP)" },
      { flag: "slug", env: "HELMSMAN_BITBUCKET_SLUG", prompt: "Bitbucket repo slug (e.g. web)" },
    ],
    authHint: "Server/DC: pat (HTTP access token, sent as Bearer).",
  },
  { key: "elk", label: "ELK (Elasticsearch)", urlEnv: "HELMSMAN_ELK_URL", authHint: "basic (username + password) or pat." },
  { key: "bamboo", label: "Bamboo", urlEnv: "HELMSMAN_BAMBOO_URL", authHint: "pat or basic." },
];

export type Flags = Record<string, string>;

export function parseArgs(argv: string[]): { positional: string[]; flags: Flags } {
  const positional: string[] = [];
  const flags: Flags = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a.startsWith("--")) {
      const body = a.slice(2);
      const eq = body.indexOf("=");
      if (eq >= 0) flags[body.slice(0, eq)] = body.slice(eq + 1);
      else {
        const next = argv[i + 1];
        if (next && !next.startsWith("--")) {
          flags[body] = next;
          i++;
        } else flags[body] = "true";
      }
    } else positional.push(a);
  }
  return { positional, flags };
}

/** Resolved at call time so tests (and HELMSMAN_ENV_FILE) can redirect the output file. */
export function envFilePath(): string {
  return process.env.HELMSMAN_ENV_FILE ?? "./.helmsman/helmsman.env";
}

/** Merge endpoint vars into the gitignored env file, preserving existing entries. */
export function upsertEnv(vars: Record<string, string>): void {
  const path = envFilePath();
  const dir = dirname(path);
  if (dir && dir !== ".") mkdirSync(dir, { recursive: true });
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const map = new Map<string, string>();
  for (const l of existing.split("\n")) {
    const line = l.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq > 0) map.set(line.slice(0, eq), line.slice(eq + 1));
  }
  for (const [k, v] of Object.entries(vars)) if (v) map.set(k, v);
  const out = ["# Helmsman endpoints — generated by `pnpm onboard` (gitignored)"];
  for (const [k, v] of map) out.push(`${k}=${v}`);
  writeFileSync(path, out.join("\n") + "\n");
}

export function credentialFromFlags(flags: Flags): Credential | undefined {
  switch (flags.kind) {
    case "basic":
      if (!flags.username || flags.password === undefined) return undefined;
      return { kind: "basic", username: flags.username, password: flags.password };
    case "oauth": {
      const accessToken = flags["access-token"] ?? flags.token;
      return accessToken ? { kind: "oauth", accessToken } : undefined;
    }
    case "pat":
      if (!flags.token) return undefined;
      return { kind: "pat", token: flags.token, scheme: flags.scheme === "basic-username" ? "basic-username" : "bearer" };
    default:
      return undefined;
  }
}

/** Store one app's endpoint + credential without prompting (flag-driven). */
export async function onboardAppNonInteractive(app: AppSpec, flags: Flags, vault: Vault): Promise<boolean> {
  const cred = credentialFromFlags(flags);
  if (!cred) return false;
  await vault.set(app.key, cred);
  const envVars: Record<string, string> = {};
  if (flags.url) envVars[app.urlEnv] = flags.url;
  for (const extra of app.extraEnv ?? []) if (flags[extra.flag]) envVars[extra.env] = flags[extra.flag]!;
  if (Object.keys(envVars).length) upsertEnv(envVars);
  return true;
}
